version: "2.1"

services:
  postgres:
    image: postgres
    restart: always
    healthcheck:
      test: pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_DB: adapt

  backend:
    restart: always
    volumes:
      - ./templates:/usr/share/adapt/templates
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    restart: always
    depends_on:
      - backend
